var countryStateInfo = {
    "Ilocos Region (Region I)": {
      "Ilocos Norte": {
        "Adams": ["2922"],
        "Bacarra" : ["2916"],
        "Badoc" : ["2904"],
        "Bangui" : ["2920"],
        "Batac" : ["2906"],
        "Burgos" : ["2918"],
        "Carasi" : ["2911"],
        "Currimao" : ["2903"],
        "Dingras" : ["2913"],
        "Dumalneg" : ["2921"],
        "Banna (formerly Espiritu)" : ["2908"],
        "Laoag City" : ["2900"],
        "Marcos" : ["2907"],
        "Nueva Era" : ["2909"],
        "Pagudpud" : ["2919"],
        "Paoay" : ["2902"],
        "Pasuquin" : ["2917"],
        "Piddig" : ["2912"],
        "Pinili" : ["2905"],
        "San Nicolas" : ["2901"],
        "Sarrat" : ["2914"],
        "Solsona" : ["	2910"],
        "Vintar" : ["2915"],
      },
    "ilocos Sur": {
        "Vigan": ["2700"],
        "Tagudin": ["2714"],
        "Suyo": ["	2715"],
        "	Sugpon": ["	2717"],
        "Sinait": ["	2733"],
        "Sigay": ["	2719"],
        "Santiago": ["	2707"],
        "Santa Maria": ["	2705"],
        "Santa Lucia": ["2712"],
        "Santa Cruz": ["	2713"],
        "Santa Catalina": ["2701"],
        "Santa": ["2703"],
        "San Vicente": ["	2726"],
        "San Juan (Lapog)": ["	2731"],
        "San Ildefonso": ["2728"],
        "San Esteban": ["2706"],
        "San Emilio": ["	2722"],
        "Salcedo (Baugen)": ["	2711"],
        "Quirino (Angkaki)": ["	2721"],
        "Narvacan": ["2704"],
        "Nagbukel": ["2725"],
        "Magsingal": ["	2730"],
        "Lidlidda": ["2723"],
        "Gregorio del Pilar (Concepcion)": ["2720"],
        "Galimuyod": ["	2709"],
        "	Cervantes": ["2718"],
        "Caoayan": ["2702"],
        "Candon": ["	2710"],
        "Cabugao": ["2732"],
        "	Burgos": ["2724"],
        "Bantay": ["2727"],
        "Banayoyo": ["2708"],
        "	Alilem": ["2716"],

      },



    },
    "Cagayan Valley (Region II)": {
        "Ilocos Norte": {
          "Adams": ["2922"],
        },
      },
      "Central Luzon (Region III)": {
        "Ilocos Norte": {
          "Adams": ["2922"],
        },
      },
      "CALABARZON (Region IV-A)": {
        "Ilocos Norte": {
          "Adams": ["2922"],
        },
      },
    "MIMAROPA (Region IV-B)": {
        "Ilocos Norte": {
          "Adams": ["2922"],
        },
      },
    "Bicol Region (Region V)": {
        "Ilocos Norte": {
          "Adams": ["2922"],
        },
      },
    "Western Visayas (Region VI)": {
        "Ilocos Norte": {
          "Adams": ["2922"],
        },
      },
    "Central Visayas (Region VII)": {
        "Ilocos Norte": {
          "Adams": ["2922"],
        },
      },
    "Zamboanga Peninsula (Region IX)": {
        "Zambaonga del Sur": {
            "Dimataling": ["7032"],
            "Pitogo": ["7033"],
            "Tabina": ["7034"],
            "Margosatubig": ["7035"],
            "Vincenzo A. Sagun": ["7036"],
            "Lapuyan": ["7037"],
            "Midsalip": ["7021"],
            "Sominot (Don Mariano Marcos)": ["7022"],
            "Molave": ["7023"],
            "Ramon Magsaysay (Liargo)": ["7024"],
            "Mahayag": ["7026"],
            "Josefina": ["7027"],
            "Dumingag": ["7028"],
            "San Miguel": ["7029"],
            "Dinas": ["7030"],
            "San Pablo": ["7031"],
            "Tukuran": ["7019"],
            "Aurora": ["7020"],
            "Pagadian": ["7016"],
            "Labangan": ["7017"],
            "Bayog": ["7011"],
            "Zamboanga City": ["7000"],
            "Kumalarang": ["7013"],
            "Lakewood": ["7014"],
            "Dumalinao": ["7015"],
            "Guipos": ["7042"],
            "Tigbao": ["7043"],
        },
        "Zambaonga Simbugay": {
            "Ipil": ["7001"],
            "Roseller T. Lim": ["7002"],
            "Titay": ["7003"],
            "Naga": ["7004"],
            "Kabasalan": ["7005"],
            "Siay": ["7006"],
            "Imelda": ["7007"],
            "Payao": ["7008"],
            "Buug": ["7009"],
            "Mabuhay": ["7010"],
            "Talusan": ["7012"],
            "Malangas": ["7038"],
            "Diplahan": ["7039"],
            "Alicia": ["7040"],
            "Olutanga": ["7041"],
        },
        "Zambaonga del Norte": {
            "Dipolog": ["7100"],
            "Dapitan": ["7101"],
            "Pres. Manuel A. Roxas": ["7102"],
            "Sibutad": ["7103"],
            "Rizal": ["7104"],
            "Piñan": ["7105"],
            "Polanco": ["7106"],
            "Mutia": ["7107"],
            "Sergio Osmeña Sr.": ["7108"],
            "Katipunan": ["7109"],
            "Manukan": ["7110"],
            "Jose Dalman (Ponot)": ["7111"],
            "Sindangan": ["7112"],
            "Siayan": ["7113"],
            "Salug": ["7114"],
            "Liloy": ["7115"],
            "Tampilisan": ["7116"],
            "Labason": ["7117"],
            "Gutalac": ["7118"],
            "La Libertad": ["7119"],
            "Siocon": ["7120"],
            "Sirawai": ["7121"],
            "Sibuco": ["7122"],
            "Baliguian": ["7123"],
            "Kalawit": ["7124"],
            "Leon B. Postigo": ["7125"],
            "Godod": ["7126"],
        },
      },
    "Northern Mindanao (Region X)": {
        "Misamis Oriental": {
                "Villanueva": ["9002"],
                "Talisayan": ["9012"],
                "Sugbongcogon": ["9009"],
                "Salay": ["9007"],
                "Opol": ["9016"],
                "Naawan": ["9023"],
                "Medina": ["9013"],
                "Manticao": ["9024"],
                "Magsaysay": ["9015"],
                "Lugait": ["9025"],
                "Libertad": ["9021"],
                "Lagonglong": ["9006"],
                "Laguindingan": ["9019"],
                "Kinoguitan": ["9010"],
                "Jasaan": ["9003"],
                "Initao": ["9022"],
                "Gitagum": ["9020"],
                "Gingoog City": ["9014"],
                "El Salvador": ["9017"],
                "Claveria": ["9004"],
                "Cagayan de Oro City": ["9000"],
                "Binuangan": ["9008"],
                "Balingoan": ["9011"],
                "Balingasag": ["9005"]
 },
    "Misamis Occidental": {
                "Tudela": ["7202"],
                "Tangub City": ["7214"],
                "Sinacaban": ["7203"],
                "Plaridel": ["7209"],
                "Panaon": ["7205"],
                "Ozamis City": ["7200"],
                "Oroquieta City": ["7207"],
                "Lopez Jaena": ["7208"],
                "Jimenez": ["7204"],
                "Don Victoriano Chiongbian": ["7216"],
                "Concepcion": ["7213"],
                "Clarin": ["7201"],
                "Bonifacio": ["7215"],
                "Calamba": ["7210"],
                "Baliangao": ["7211"],
                "Aloran": ["7206"]
          },
    "Lanao del Norte": {
                "Tubod": ["9209"],
                "Tangcal": ["9220"],
                "Tagoloan": ["9222"],
                "Sultan Naga Dimaporo (formerly Karomatan)": ["9215"],
                "Sapad": ["9213"],
                "Salvador": ["9212"],
                "Poona Piagapo": ["9204"],
                "Pantar": ["9218"],
                "Pantao Ragat": ["9208"],
                "Nunungan": ["9216"],
                "Munai": ["9219"],
                "Matungao": ["9203"],
                "Maigo": ["9206"],
                "Magsaysay": ["9221"],
                "Linamon": ["9201"],
                "Lala": ["9211"],
                "Kolambugan": ["9207"],
                "Kauswagan": ["9202"],
                "Kapatagan": ["9214"],
                "Iligan City": ["9200"],
                "Baroy": ["9210"],
                "Baloi": ["9217"],
                "Bacolod": ["9205"]
          },
    "Camiguin": {
                "Sagay": ["9103"],
                "Mambajao": ["9100"],
                "Mahinog": ["9101"],
                "Guinsiliban": ["9102"],
                "Catarman": ["9104"],
                "Valencia": ["8709"],
      },
    "Bukidnon": {
                "Valencia": ["8709"],
                "Talakag": ["8708"],
                "Sumilao": ["8701"],
                "San Fernando": ["8711"],
                "Quezon": ["8715"],
                "Phillips": ["8705"],
                "Pangantucan": ["8717"],
                "Musuan": ["8710"],
                "Maramag": ["8714"],
                "Manolo Fortich": ["8703"],
                "Malitbog": ["8704"],
                "Malaybalay": ["8700"],
                "Libona": ["8706"]
    },
    "Agusan del Norte": {
                "Lantapan": ["8722"],
                "Kitaotao": ["8716"],
      },
    "Aurora": {
                "Sapang dalaga": ["	7212"],
                "Tagoloan": ["9001"],
        },
},
    "Davao Region (Region XI)": {
        "Davao Oriental": {
                "Tarragona": ["8201"],
                "San Isidro": ["8209"],
                "Mati": ["8200"],
                "Manay": ["8202"],
                "Lupon": ["8207"],
                "Gov. Generoso": ["8210"],
                "Cateel": ["8205"],
                "Caraga": ["8203"],
                "Boston": ["8206"],
                "Banaybanay": ["8208"],
                "Baganga": ["8204"],
        },
    "Davao Occidental": {
                "Sarangani": ["8015"],
                "Santa Maria": ["8011"],
                "Malita": ["8012"], 
                "Jose Abad Santos": ["8014"],
                "Don Marcelino": ["8013"]
          },
    "Davao del Sur": {
                "University of Mindanao": ["8026"],
                "Toril": ["8025"],
                "Tibungco": ["8024"],
                "Talomo": ["8023"],
                "Sulop": ["8009"],
                "Santa Cruz": ["8001"],
                "Padada": ["8007"],
                "Mintal": ["8022"],
                "Matina": ["8021"],
                "Matanao": ["8003"],
                "Mandug": ["8020"],
                "Malalag": ["8010"],
                "Magsaysay": ["8004"],
                "Kiblawan": ["8008"],
                "Hagonoy": ["8006"],
                "Digos": ["8002"],
                "Davao International Airport": ["8019"],
                "Davao City": ["8000"],
                "Calinan": ["8018"],
                "Bunawan": ["8017"],
                "Bansalan": ["8005"],
                "Ateneo": ["8016"],
          },
    "Davao de Norte": {
                "Talaingod": ["8107"],
                "Tagum": ["8100"],
                "Santo Tomas": ["8112"],
                "San Isidro": ["8121"],
                "Samal": ["8119"],
                "Panabo": ["8105"],
                "New Corella": ["8104"],
                "Kaputian": ["8120"],
                "Kapalong": ["8113"],
                "Carmen": ["8101"],
                "Braulio E. Dujali": ["8106"],
                "Babak": ["8118"],
                "Asuncion (formerly Saug)": ["8102"],
          },
    "Davao de Oro": {
                "Pantukan": ["8809"],
                "New Bataan": ["8804"],
                "Nabunturan": ["8800"],
                "Montevista": ["8801"],
                "Monkayo": ["8805"],
                "Mawab": ["8802"],
                "Maragusan (formerly San Mariano)": ["8808"],
                "Maco": ["8806"],
                "Mabini": ["8807"],
                "Laak (formerly San Vicente)": ["8810"],
                "Compostela": ["8803"],
          },

      },

"SOCCSKSARGEN (Region XII)": {
        "Sultan Kudarat": {
            "Pres. Quirino": ["9804"],
            "Palimbang": ["9809"],
            "Mariano Marcos": ["9802"],
            "Lutayan": ["9803"],
            "Lebak (Salaman)": ["9807"],
            "Kalamansig": ["9808"],
            "Isulan": ["9805"],
            "Esperanza (Ampatuan)": ["9806"],
            "Columbio": ["9801"],
            "Bagumbayan": ["9810"],
            "Tacurong": ["9800"],
            "Sen. Ninoy Aquino": ["9811"],
        },
 "South Cotabato": {
            "Tupi": ["9505"],
            "Tantangan": ["9510"],
            "Tampakan": ["9507"],
            "Surallah": ["9512"],
            "Sto. Niño": ["9509"],
            "Polomolok": ["9504"],
            "Norala": ["9508"],
            "Lake Sebu": ["9518"],
            "Koronadal": ["9506"],
            "Gen. Santos City": ["9500"],
            "Banga": ["9511"],
            "T'boli": ["9513"],
          },
"Sarangani": {
            "Malungon": ["9503"],
            "Malapatan": ["9516"],
            "Maitum": ["9515"],
            "Maasim": ["9502"],
            "Glan": ["9517"],
            "Alabel": ["9501"],
          },
"North Cotabato": {
            "Tulunan": ["9403"],
            "Pre. Roxas": ["9405"],
            "Pikit": ["9409"],
            "Pigkawayan": ["9412"],
            "M'lang": ["9402"],
            "Midsayap": ["9410"],
            "Matalam": ["9406"],
            "Makilala": ["9401"],
            "Magpet": ["9404"],
            "Libungan": ["9411"],
            "Kidapawan": ["9400"],
            "Kabacan": ["9407"],
            "Carmen": ["9408"],
            "Banisilan": ["9416"],
            "Arakan": ["9417"],
            "Antipas": ["9414"],
            "Aleosan": ["9415"],
            "Alamada": ["9413"],
          },
      },

"Caraga (Region XIII)": {
    "Surigao del Sur": {
            "Tandag": ["8300"],
            "Tago": ["8302"],
            "Tagbina": ["8308"],
            "San Miguel": ["8301"],
            "San Agustin": ["8305"],
            "Marihatag": ["8306"],
            "Malixi": ["8319"],
            "Madrid": ["8316"],
            "Lingig": ["8312"],
            "Lianga": ["8307"],
            "Lanuza": ["8314"],
            "Hinatuan": ["8310"],
            "Cortez": ["8313"],
            "Carrascal": ["8318"],
            "Cantilan": ["8317"],
            "Cagwait": ["8304"],
            "Bislig": ["8311"],
            "Bayabas": ["8303"],
            "Barobo": ["8309"],
        },
"Dinagat Island": {
            "Tubajon": ["8426"],
            "San Jose": ["8427"],
            "Loreto": ["8415"],
            "Libjo (formerly Albor)": ["8414"],
            "Dinagat": ["8412"],
            "Cagdianao": ["8411"],
            "Basilisa (formerly Rizal)": ["8413"],
         },
 "Surigao del Norte": {
            "Tagana-an": ["8403"],
            "Tubod": ["8406"],
            "Surigao City": ["8400"],
            "Sta. Monica": ["8422"],
            "Socorro": ["8416"],
            "Sison": ["8404"],
            "San Isidro": ["8421"],
            "San Francisco": ["8401"],
            "San Benito": ["8423"],
            "Placer": ["8405"],
            "Pilar": ["8420"],
            "Malimono": ["8402"],
            "Mainit": ["8407"],
            "Gigaquit": ["8409"],
            "Gen. Luna": ["8419"],
            "Del Carmen": ["8418"],
            "Dapa": ["8417"],
            "Claver": ["8410"],
            "Burgos": ["8424"],
            "Bacuag": ["8408"],
            "Alegria": ["8425"],
            "Carmen": ["8315"],
          },
  "Agusan del Sur": {
            "Veruela": ["8509"],
            "Trento": ["8505"],
            "Talacogon": ["8510"],
            "Sta. Josefa": ["8512"],
            "Sibagat": ["8503"],
            "San Luis": ["8511"],
            "San Francisco": ["8501"],
            "Rosario": ["8504"],
            "Prosperidad": ["8500"],
            "Loreto": ["8507"],
            "La Paz": ["8508"],
            "Esperanza": ["8513"],
            "Bunawan": ["8506"],
            "Bayugan": ["8502"],
          },
"Agusan del Norte": {
            "Tubay": ["8606"],
            "Santiago": ["8608"],
            "Remedios T. Romualdez": ["8611"],
            "Nasipit": ["8602"],
            "Magallanes": ["8604"],
            "Las Nieves": ["8610"],
            "Kitcharao": ["8609"],
            "Jabonga": ["8607"],
            "Carmen": ["8603"],
            "Cabadbaran": ["8605"],
            "Butuan City": ["8600"],
            "Buenavista": ["8601"],
          },
      },

      "Cordillera Administrative Region (CAR)": {
        "Ilocos Norte": {
          "Adams": ["2922"],
        },
      },

      "National Capital Region (NCR)": {
        "Ilocos Norte": {
          "Adams": ["2922"],
        },
      },

      "Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)": {
        "Basilan": {
            "Lantawan": ["7301"],
            "Lamitan": ["7302"],
            "Maluso": ["7303"],
            "Tipo-Tipo": ["7304"],
            "Sumisip": ["7305"],
            "Tuburan": ["7306"],
        },
 "Julu Sulu": {
            "Jolo": ["7400"],
            "Patikul": ["7401"],
            "Old Panamao": ["7402"],
            "Talipao": ["7403"],
            "Luuk (Omar)": ["7404"],
            "Pata": ["7405"],
            "Banguingui (Tongkil)": ["7406"],
            "Indanan": ["7407"],
            "Parang": ["7408"],
            "Maimbung": ["7409"],
            "Tapul": ["7410"],
            "Lugus": ["7411"],
            "Siasi": ["7412"],
            "Hadji Panglima Tahil": ["7413"],
            "Pangutaran": ["7414"],
            "Panglima Estino (New Panamao)": ["7415"],
            "Kalingalan Calauang": ["7416"],
        },
 "Tawi-Tawi": {
            "Bongao": ["7500"],
            "Panglima Sugala (Balimbing)": ["7501"],
            "Tandubas": ["7502"],
            "Sapa-Sapa": ["7503"],
            "South Ubian": ["7504"],
            "Simunul": ["7505"],
            "Sitangkai": ["7506"],
            "Turtle Islands (Taganak)": ["7507"],
            "Mapun (Cagayan de Sulu)": ["7508"],
            "Languyan": ["7509"],
            "Sibutu": ["7510"],
        },
        "Lanao del Sur": {
            "Pantar": ["9218"],
            "Malabang": ["9300"],
            "Picong (Sultan Gumander)": ["9301"],
            "Balabagan": ["9302"],
            "Marogong": ["9303"],
            "Tubaran": ["9304"],
            "Butig": ["9305"],
            "Lumbayanague": ["9306"],
            "Lumbatan": ["9307"],
            "Lumbaca-Unayan and Macadar Andong": ["9308"],
            "Bayang": ["9309"],
            "Binidayan": ["9310"],
            "Ganassi": ["9311"],
            "Pagayawan": ["9312"],
            "Pualas": ["9313"],
            "Madamba": ["9314"],
            "Madalum": ["9315"],
            "Bacolod-Kalawi (Bacolod Grande)": ["9316"],
            "Tugaya": ["9317"],
            "Balindong": ["9318"],
            "Calanogas": ["9319"],
            "Amai Manabilang (Bumbaran)": ["9320"],
            "Kapatagan": ["9322"],
            "Kapatagan": ["9700"],
            "Saguiaran": ["9701"],
            "Mulondo": ["9702"],
            "Lumba-Bayabao": ["9703"],
            "Tamparan": ["9704"],
            "Poona Bayabao": ["9705"],
            "Masiu": ["9706"],
            "Bubong": ["9708"],
            "Kapai": ["9709"],
            "Piagapo": ["9710"],
            "Marantao": ["9711"],
            "Taraka": ["9712"],
            "Ditsaan-Ramain": ["9713"],
            "Buadiposo-Buntong": ["9714"],
            "Maguing": ["9715"],
            "Wao": ["9716"],
        },
        "Maguindanao": {
            "Cotabato City": ["9600"],
            "Datu Odin Sinsuat (Dinaig)": ["9601"],
            "Upi": ["9602"],
            "South Upi": ["9603"],
            "Parang": ["9604"],
            "Sultan Kudarat": ["9605"],
            "Kabuntalan": ["9606"],
            "Datu Piang": ["9607"],
            "Shariff Aguak (Maganoy)": ["9608"],
            "Ampatuan": ["9609"],
            "Pagalungan": ["9610"],
            "Sultan sa Barongis": ["9611"],
            "Talayan": ["9612"],
            "Matanog": ["9613"],
            "Barira": ["9614"],
            "Buldon": ["9615"],
            "Buluan": ["9616"],
            "Datu Paglas": ["9617"],
            "Gen. S.K. Pendatun": ["9618"],
            "Mangudadatu": ["9620"],
            "Datu Abdullah Sangki": ["9621"],
            "Datu Anggal Midtimbang": ["9622"],
            "Datu Blah T. Sinsuat": ["9623"],
            "Datu Hoffer Ampatuan": ["9624"],
            "Datu Salibo": ["9625"],
            "Datu Saudi-Ampatuan": ["9626"],
            "Datu Unsay": ["9627"],
            "Guindulungan": ["9628"],
            "Mamasapano": ["9629"],
            "Northern Kabuntalan": ["9630"],
            "Datu Montawal (Pagagawan)": ["9631"],
            "Paglat": ["9632"],
            "Pandag": ["9633"],
            "Rajah Buayan": ["9634"],
            "Shariff Saydona Mustapha": ["9635"],
            "Sultan Mastura": ["9636"],
            "Sultan Sumagka (Talitay)": ["9637"],
        },

  },
};
  
  window.onload = function () {
    const countrySelection = document.querySelector("#Country");
    const stateSelection = document.querySelector("#State");
    const citySelection = document.querySelector("#City");
    const zipSelection = document.querySelector("#Zip");
  
    stateSelection.disabled = true;
    citySelection.disabled = true;
    zipSelection.disabled = true;
  
    for (let country in countryStateInfo) {
      countrySelection.options[countrySelection.options.length] = new Option(
        country,
        country
      );
    }
  
    countrySelection.onchange = (e) => {
      stateSelection.disabled = false;
      stateSelection.length = 1;
      citySelection.length = 1;
      zipSelection.length = 1;
  
      let selectedCountry = countryStateInfo[e.target.value];
  
      for (let state in selectedCountry) {
        stateSelection.options[stateSelection.options.length] = new Option(
          state,
          state
        );
      }
    };
  
    stateSelection.onchange = (e) => {
      citySelection.disabled = false;
      citySelection.length = 1;
      zipSelection.length = 1;
  
      let selectedCities = Object.keys(countryStateInfo[countrySelection.value][e.target.value]);
  
      for (let city of selectedCities) {
        citySelection.options[citySelection.options.length] = new Option(
          city,
          city
        );
      }
    };
  
    citySelection.onchange = (e) => {
      zipSelection.disabled = false;
      zipSelection.length = 1;
  
      let selectedCity = e.target.value;
      let zipCodes = countryStateInfo[countrySelection.value][stateSelection.value][selectedCity];
  
      for (let zip of zipCodes) {
        zipSelection.options[zipSelection.options.length] = new Option(zip, zip);
      }
    };
  };
  

    
    
    
      